#!/bin/bash
set -e
echo "Updating MPD configuration"
MPDCONF="/etc/mpd.conf"
VARMPD="/var/tmp/mpd.conf"

cmd="sudo chown mpd:audio ${VARMPD}"
echo ${cmd};${cmd}
if [[ ! -f ${MPDCONF} ]]; then
    echo "${MPDCONF} not found - restoring"
	cmd="sudo cp ${VARMPD} ${MPDCONF}"
	echo ${cmd};${cmd}
else  
	echo "${MPDCONF} exists"
    cmd="sudo chown mpd:audio ${MPDCONF}"
	echo ${cmd};${cmd}
fi
systemctl daemon-reload

# End of script
